package com.question1;
//............declaring a util package for scanner class........ 
import java.util.Scanner;
//................Declaring a class............
public class TestDiamond {
//..............Main method................
	public static void main(String args[]) {
		//............creating a scanner class object........
		Scanner sc=new Scanner(System.in);
		//..........taking input...................
		  System.out.println("Enter the Row Numbers is: ");
	//..........calling diamondpattern class..............
		DiamondPattern d=new DiamondPattern();
		d.calculateRow(6,6,6,6);
		//................scanner close...........
		sc.close();
	}//...........end of main method .............
}
//....................end of class...................
